version: 0.2

phases:
  build:
    commands:
      # AWS クレデンシャルの取得
      - curl -qL -o aws_credentials.json 169.254.170.2${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}
      - AWS_ACCESS_KEY_ID=`jq -r '.AccessKeyId' aws_credentials.json`
      - AWS_SECRET_ACCESS_KEY=`jq -r '.SecretAccessKey' aws_credentials.json`
      - AWS_SESSION_TOKEN=`jq -r '.Token' aws_credentials.json`
      # aws-nukeのダウンロード
      - wget -q https://github.com/rebuy-de/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64 -O aws-nuke
      - chmod u+x aws-nuke
      # aws-nuke設定ファイル取得
      - aws s3 cp s3://${NUKE_CONFIG_BUCKET_ID}/nuke-config.yaml .
      # aws-nukeの実行
      - ./aws-nuke -c nuke-config.yaml --no-dry-run --quiet --force --force-sleep 3 --access-key-id $AWS_ACCESS_KEY_ID --secret-access-key $AWS_SECRET_ACCESS_KEY --session-token $AWS_SESSION_TOKEN
